_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.9.19
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
            "2":
                - 1
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.9.19
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
Msl_run:
    value: 1
anormly_ratio:
    value: 1
batch_size:
    value: 32
data_path:
    value: dataset/SMAP
dataset:
    value: SMAP
input_c:
    value: 25
k:
    value: 3
local_window:
    value: 5
lr:
    value: 0.0001
mode:
    value: train
model_save_path:
    value: checkpoints
num_epochs:
    value: 1
output_c:
    value: 25
pretrained_model:
    value: null
rand_rate:
    value: 0.1
seed:
    value: 2023
sparse:
    value: true
stride:
    value: 7
vary_len:
    value: 1
wandb:
    value: true
win_size:
    value: 100
